# See https://www.appveyor.com/docs/lang/ruby/
version: 0.1.0.{build}-{branch}
cache:
  - .bundle

matrix:
  fast_finish: true

environment:
  BOLT_WINRM_USER: roddypiper
  BOLT_WINRM_HOST: localhost
  BOLT_WINRM_PORT: 5985
  matrix:
    - RUBY_VERSION: 200
    - RUBY_VERSION: 24

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - git submodule update --init --recursive
  - bundle config --local path .bundle
  - bundle install --jobs 3 --retry 3

build: off

before_test:
  - ps: |
      ruby -v
      gem -v
      bundle -v
      type Gemfile.lock
      $computer = [ADSI]"WinNT://."
      $user = $computer.Create('user', $ENV:BOLT_WINRM_USER)
      Add-Type -AssemblyName System.Web
      $ENV:BOLT_WINRM_PASSWORD = "&aA4" + [System.Web.Security.Membership]::GeneratePassword(10, 3)
      $user.SetPassword($ENV:BOLT_WINRM_PASSWORD)
      $user.SetInfo()
      $group = [ADSI]"WinNT://./Remote Management Users,group"
      # cannot use '.' for host in the user path per
      # https://stackoverflow.com/questions/20286306/error-while-adding-a-local-group-to-local-user-using-powershell
      $group.Add("WinNT://$ENV:COMPUTERNAME/$ENV:BOLT_WINRM_USER,user")

test_script:
  - bundle exec rake appveyor
  - cd modules/boltlib
  - bundle exec rake spec
